# Generated by Django 5.0 on 2024-03-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fnm', models.CharField(max_length=20)),
                ('lnm', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254)),
                ('passwowrd', models.CharField(max_length=10)),
            ],
        ),
    ]
