# Generated by Django 5.0 on 2024-03-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='passwowrd',
            new_name='password',
        ),
    ]
