# Generated by Django 5.0 on 2024-03-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_passwowrd_newuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newuser',
        ),
    ]
