# Generated by Django 5.0 on 2024-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='profil_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
